on:
  # schedule:
  #   - cron: 8 * * * *  # run on 8th minute of every hour
  workflow_dispatch:


jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Make API request and append to file
        run: |
          RESPONSE=$(curl -s -X POST -H "Authorization: Basic $(echo -n '${{ secret.SPOTIFY_CLIENT_ID}}:${{ secret.SPOTIFY_CLIENT_SECRET}}' | base64)" -d grant_type=client_credentials https://accounts.spotify.com/api/token)
          echo "$RESPONSE" >> data.txt