name: Update data

on:
  # schedule:
  #   - cron: 8 * * * *  # run on 8th minute of every hour
  workflow_dispatch:


jobs:
  updateData:
    runs-on: ubuntu-latest
    steps:
    - name: Request Spotify Access Key
      run: |
        AUTH_RES=$(curl -s -X POST -H "Authorization: Basic $(echo -n '${{ secrets.SPOTIFY_CLIENT_ID }}:${{ secrets.SPOTIFY_CLIENT_SECRET }}' | base64 -w 0)" -d grant_type=client_credentials https://accounts.spotify.com/api/token)
    
    - name: Extract Access Key
      run: |
        ACCESSKEY=$(echo "$AUTH_RES" | sed -n "s/.*key:\([^']*\)'.*/\1/p")


  updateData:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: pip install pyYAML
        run: |
          pip install pyYAML requests

      - name: Run distractibleScript.py
        run: |
          python scripts/distractibleScript.py
        
      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Commit and push changes
        run: |
          git add .github/workflows
          git commit -m "Distractible Data Update"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
